title: My WildCat Studios Portfolio 
description: >-cc818852.github.io
         This is my portfolio showcasing my projects and skills.
baseurl: "" 
url: "https://cc818852.github.io"
theme: jekyll-theme-merlot
