title: My WildCat Studios Portfolio description: >-
         This is my portfolio showcasing my projects and skills.
baseurl: "" 
url: "https://YOURUSERNAME.github.io" #CC818852
theme: jekyll-theme-merlot # replace with your chosen theme from the list
